default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: true
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: root
  password: pass
  host: mysql
  database: rails_development

test:
  <<: *default
  username: root
  password: pass
  host: mysql
  database: application_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
